# stage: 1
FROM node:10 as react-build
WORKDIR /app
COPY . ./
RUN yarn
RUN yarn build

# stage: 2 — the production environment
FROM react-build
RUN yarn build
RUN yarn global add serve
ENTRYPOINT ["serve", "-s", "build"]
EXPOSE 5000