# stage: 1
FROM node:10 as react-build
WORKDIR /app
COPY . ./
RUN yarn
RUN yarn build
RUN dir

# stage: 2 — the production environment
FROM node:10
COPY — from=react-build
RUN yarn global add serve
RUN serve -s build 
EXPOSE 5000